version: "2"
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    network_mode: host
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./etc/conf.d/my.cnf:/etc/my.cnf
      - /app/mysql/data:/var/lib/mysql
      - /app/mysql/log:/var/log/mysql
      - /app/mysql/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
