version: "3.3"
services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_USER=houfachao
      - HTTP_PASS=geek1994
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - "./dnsmasq.conf:/etc/dnsmasq.conf"