version: "2.0"
services:
  elasticsearch:
    image: docker.io/elasticsearch:7.6.2
    container_name: es
    environment:
      - node.name=${HOSTNAME}
      - cluster.name=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - discovery.type=single-node #集群模式去掉
      - TAKE_FILE_OWNERSHIP=true # 如果不加会报 Error opening log file ‘logs/gc.log’: Permission denied
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /app/elasticsearch-standalone/data:/usr/share/elasticsearch/data:rw
      - /app/elasticsearch-standalone/logs:/usr/share/elasticsearch/logs:rw
      - ./plugins:/usr/share/elasticsearch/plugins:ro
    network_mode: "bridge"
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
