version: "2"
services:
  postgresql:
    container_name: postgresql
    image: postgres:10.8-alpine
    restart: always
    ports:
      - "6432:5432"
    expose:
      - "6432"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - ./etc/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./etc/pg_ident.conf:/etc/postgresql/pg_ident.conf
      - ./etc/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql:/var/lib/sql
      - /app/postgresql/data:/var/lib/postgresql/data
      - /app/postgresql-archive:/var/lib/postgresql-archive
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf' -c 'ident_file=/etc/postgresql/pg_ident.conf'