version: "2"
services:
  milvus:
    image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
    container_name: milvus
    ports:
      - 8530:19530
      - 8121:19121
    volumes:
      - ./conf:/var/lib/milvus/conf
      - /app/milvus/db:/var/lib/milvus/db
      - /app/milvus/logs:/var/lib/milvus/logs
      - /app/milvus/wal:/var/lib/milvus/wal
    expose:
      - 8530
      - 8121