version: "3.3"
services:
  ewomail:
    image: bestwu/ewomailserver
    hostname: mail.xxlab.tech
    container_name: ewomail
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "109:109"
      - "110:110"
      - "465:465"
      - "995:995"
      - "80:80"
      - "8080:8080"
    volumes:
      - /app/ewomail/mysql:/ewomail/mysql/data
      - /app/ewomail/vmail:/ewomail/mail
      - /app/ewomail/rainloop:/ewomail/www/rainloop/data
      - /app/ewomail/ssl/certs/:/etc/ssl/certs/
      - /app/ewomail/ssl/private/:/etc/ssl/private/
      - /app/ewomail/ssl/dkim/:/ewomail/dkim/