version: "3"
services:
  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: redis:4.0.14-alpine
    restart: always
    networks:
      - redis
    ports:
      - "26380:26379"
    expose:
      - "26380"
    volumes:
      - ./../etc/sentinel.conf:/etc/redis/sentinel.conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-sentinel /etc/redis/sentinel.conf"

networks:
  redis:
    external: true