version: '2'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - /app/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: always
    volumes:
      - /app/grafana/grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    user: root
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"