version: '2'
services:
  tinyproxy:
    container_name: tinyproxy
    image: vimagick/tinyproxy:latest
    ports:
      - 8888:8888
    volumes:
      - /app/tinyproxy/log:/var/log/tinyproxy
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
    restart: always
