version: "2"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 5300:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    expose:
      - 5300