version: "2"
services:
  redis-master:
    container_name: redis-master
    image: redis:4.0.14-alpine
    restart: always
    networks:
      redis:
        ipv4_address: 172.22.0.2
    hostname: redis-master
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./etc/redis-master.conf:/etc/redis/redis-master.conf
      - /app/redis-master/log/:/var/log/redis
      - /app/redis-master/lib:/var/lib/redis
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-server /etc/redis/redis-master.conf"

  redis-slave:
    container_name: redis-slave
    image: redis:4.0.14-alpine
    restart: always
    networks:
      redis:
        ipv4_address: 172.22.0.3
    ports:
      - "6380:6379"
    expose:
      - "6380"
    volumes:
      - ./etc/redis-slave.conf:/etc/redis/redis-master.conf
      - /app/redis-slave/log/:/var/log/redis
      - /app/redis-slave/lib:/var/lib/redis/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-server /etc/redis/redis-master.conf"

  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: redis:4.0.14-alpine
    restart: always
    networks:
      redis:
        ipv4_address: 172.22.1.1
    ports:
      - "26379:26379"
    expose:
      - "26379"
    volumes:
      - ./etc/sentinel.conf:/etc/redis/sentinel.conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-sentinel /etc/redis/sentinel.conf"

  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: redis:4.0.14-alpine
    restart: always
    networks:
      redis:
        ipv4_address: 172.22.1.2
    ports:
      - "26380:26379"
    expose:
      - "26380"
    volumes:
      - ./etc/sentinel.conf:/etc/redis/sentinel.conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-sentinel /etc/redis/sentinel.conf"

  redis-sentinel-3:
    container_name: redis-sentinel-3
    image: redis:4.0.14-alpine
    restart: always
    networks:
      redis:
        ipv4_address: 172.22.1.3
    ports:
      - "26381:26379"
    expose:
      - "26381"
    volumes:
      - ./etc/sentinel.conf:/etc/redis/sentinel.conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-sentinel /etc/redis/sentinel.conf"

networks:
  redis:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/16
        gateway: 172.22.0.1