version: '3'

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: "no"
    hostname: 'gitlab.xxlab.tech'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.xxlab.tech'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '80:80'
      - '2224:22'
    volumes:
      - '/app/gitlab/config:/etc/gitlab'
      - '/app/gitlab/logs:/var/log/gitlab'
      - '/app/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'