version: "2"
services:
  frpc:
    container_name: frpc
    image: snowdreamtech/frpc
    restart: always
    network_mode: host
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
