version: "2.2"
services:
  nginx:
    container_name: nginx
    image: nginx:1.17.0-alpine
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - /app/nginx/log:/var/log/nginx
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/db:/etc/nginx/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
