version: "2.2"
services:
  nginx:
    container_name: nginx
    image: nginx:1.17.0-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - /app/nginx/log:/var/log/nginx
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/db:/etc/nginx/db
      - /app/nginx/cache:/tmp/nginx/cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  goaccess:
    container_name: goaccess
    image: allinurl/goaccess
    restart: unless-stopped
    network_mode: host
    command: --no-global-config --config-file=/goaccess/config/goaccess.conf
    depends_on:
      - nginx
    volumes:
      - ./etc/goaccess/goaccess.conf:/goaccess/config/goaccess.conf:ro
      - ./etc/goaccess/GeoLite2-City.mmdb:/goaccess/data/GeoLite2-City.mmdb
      - /app/nginx/log/:/goaccess/:ro
      - /app/www/goaccess:/var/www/goaccess
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
