version: "2"
services:
  baidunetdisk:
    container_name: baidunetdisk
    image: johngong/baidunetdisk:latest
    restart: always
    ports:
    - 5800:5800
    - 5900:5900
    volumes:
      - /app/download:/config/baidunetdiskdownload
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
