version: "2.0"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - nacos-standlone.env
    volumes:
      - /app/nacos/standalone-logs/:/home/nacos/logs
      - ./init.d/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    expose:
      - 9555
      - 8848
    depends_on:
      - mysql
    restart: always