version: "2.0"
services:
  nacos-standalone:
    image: nacos/nacos-server:1.3.1
    container_name: nacos-standalone
    env_file:
      - ./env/nacos.env
    volumes:
      - /app/nacos-standalone/logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    expose:
      - 9555
      - 8848
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./env/mysql.env
    volumes:
      - /app/nacos-standalone/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
