version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: "host"
    restart: "unless-stopped"
    ports:
    - 8096:8096
    volumes:
      - /app/jellyfin/config:/config
      - /app/jellyfin/cache:/cache
      - /app/jellyfin/media:/media