version: "3"
services:
  halo:
    container_name: halo
    image: halohub/halo:1.5.3
    restart: "always"
    ports:
    - "8090:8090"
    volumes:
      - /app/halo:/root/.halo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"