version: "2"
services:
  chatgpt-proxy:
    container_name: chatgpt-proxy
    image: registry.cn-beijing.aliyuncs.com/xxlab/chatgpt-proxy
    restart: always
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
