version: '3'
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.8.1
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ./config/:/usr/share/logstash/config/
    restart: always
    network_mode: host