version: "2"
services:
  ppocr:
    container_name: ppocr
    image: paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82
    restart: always
    ports:
      - "26379:26379"
    expose:
      - "26379"
    volumes:
      - /paddle:/app/ppocr
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint: "redis-sentinel /etc/redis/sentinel.conf"